package models

type ContentType string

const (
	ContentTypeGame      ContentType = "GAME"
	ContentTypeAIService ContentType = "AI_SERVICE"
)

type ContainerStatus string

const (
	StatusCold ContainerStatus = "COLD"
	StatusWarm ContainerStatus = "WARM"
	StatusHot  ContainerStatus = "HOT"
)

type ContentItem struct {
	ID              string          `json:"id"`
	Type            ContentType     `json:"type"`
	Theme           string          `json:"theme"`
	Title           string          `json:"title"`
	Description     string          `json:"description"`
	ThumbnailURL    string          `json:"thumbnail_url"`
	ContainerStatus ContainerStatus `json:"container_status"`
	DeploymentName  string          `json:"deployment_name"`
	PersonalScore   float64         `json:"personal_score"`
	GlobalScore     float64         `json:"global_score"`
	CombinedScore   float64         `json:"combined_score"`
}

// CrossDomainRelations maps content IDs to related content IDs
var CrossDomainRelations = map[string]string{
	// Original relations
	"game-2048":           "game-slice-master",
	"game-slice-master":   "game-tiny-fishing",
	"game-space-waves":    "game-drift-boss",
	"game-drift-boss":     "game-space-waves",
	"game-tiny-fishing":   "game-slice-master",
	"game-stickman-hook":  "game-temple-of-boom",
	"game-moto-x3m":       "game-smash-karts",
	"game-paper-io-2":     "game-narrow-one",
	"game-temple-of-boom": "game-stickman-hook",
	"game-monkey-mart":    "game-tiny-fishing",
	"game-tunnel-rush":    "game-space-waves",
	"game-narrow-one":     "game-paper-io-2",
	"game-smash-karts":    "game-moto-x3m",
	"ai-service-tech":     "game-monkey-mart",
	// FPS Arena cross-links
	"game-shell-shockers":    "game-kour-io",
	"game-kour-io":           "game-voxiom-io",
	"game-voxiom-io":         "game-bullet-force",
	"game-bullet-force":      "game-skillwarz",
	"game-skillwarz":         "game-buildnow-gg",
	"game-buildnow-gg":       "game-1v1-lol",
	"game-1v1-lol":           "game-pixel-warfare",
	"game-pixel-warfare":     "game-shell-shockers",
	// Arcade Zone cross-links
	"game-geometry-dash":     "game-color-tunnel",
	"game-color-tunnel":      "game-helix-jump",
	"game-helix-jump":        "game-stacky-bird",
	"game-stacky-bird":       "game-jet-rush",
	"game-jet-rush":          "game-count-masters",
	"game-count-masters":     "game-man-runner-2048",
	"game-man-runner-2048":   "game-geometry-dash",
	// IO World cross-links
	"game-agar-io":           "game-snake-io",
	"game-evowars-io":        "game-diep-io",
	"game-bloxd-io":          "game-cubes-2048",
	"game-cubes-2048":        "game-bloxd-io",
	"game-diep-io":           "game-agar-io",
	"game-zombs-royale":      "game-lol-beans",
	"game-snake-io":          "game-agar-io",
	"game-skribbl-io":        "game-fly-or-die",
	"game-lol-beans":         "game-zombs-royale",
	"game-fly-or-die":        "game-evowars-io",
	// Sports Hub cross-links
	"game-basketbros":        "game-basketball-stars",
	"game-basketball-stars":  "game-basket-random",
	"game-goal-gang":         "game-crazy-flips",
	"game-basket-random":     "game-basketbros",
	"game-8-ball-pool":       "game-mini-golf",
	"game-mini-golf":         "game-8-ball-pool",
	"game-crazy-flips":       "game-goal-gang",
	// Puzzle Lab cross-links
	"game-uno-online":        "game-chess",
	"game-chess":             "game-master-chess",
	"game-checkers":          "game-backgammon",
	"game-backgammon":        "game-mancala",
	"game-mahjong":           "game-checkers",
	"game-master-chess":      "game-chess",
	"game-mancala":           "game-mahjong",
	// Idle Kingdom cross-links
	"game-clicker-heroes":    "game-mr-mine",
	"game-mr-mine":           "game-doge-miner",
	"game-doge-miner":        "game-doge-miner-2",
	"game-doge-miner-2":      "game-planet-clicker",
	"game-planet-clicker":    "game-race-clicker",
	"game-race-clicker":      "game-idle-inventor",
	"game-idle-inventor":     "game-clicker-heroes",
	// Casual Play cross-links
	"game-crazy-fish":        "game-bubble-blast",
	"game-papas-pizzeria":    "game-getting-over-it",
	"game-getting-over-it":   "game-friday-night-funkin",
	"game-friday-night-funkin": "game-fireboy-watergirl",
	"game-bubble-blast":      "game-crazy-fish",
	"game-fireboy-watergirl": "game-papas-pizzeria",
	// Racing cross-links
	"game-night-city-racing": "game-mx-offroad",
	"game-mx-offroad":        "game-night-city-racing",
	// Battle Arena cross-links
	"game-rooftop-snipers":   "game-getaway-shootout",
	"game-getaway-shootout":  "game-ragdoll-archers",
	"game-ragdoll-archers":   "game-stickman-clash",
	"game-stickman-clash":    "game-tank-stars",
	"game-tank-stars":        "game-castle-craft",
	"game-castle-craft":      "game-iron-legion",
	"game-iron-legion":       "game-hex-empire",
	"game-hex-empire":        "game-rocket-bot-royale",
	"game-rocket-bot-royale": "game-horde-killer",
	"game-horde-killer":      "game-superhot",
	"game-superhot":          "game-time-shooter-2",
	"game-time-shooter-2":    "game-street-fighter-2",
	"game-street-fighter-2":  "game-rooftop-snipers",
}

// DefaultContent returns the initial content items for the demo
func DefaultContent() []ContentItem {
	return []ContentItem{
		// CrazyGames
		{
			ID:              "game-2048",
			Type:            ContentTypeGame,
			Theme:           "puzzle",
			Title:           "2048",
			Description:     "Classic number puzzle - merge tiles to reach 2048",
			ThumbnailURL:    "/assets/game-2048.png",
			ContainerStatus: StatusCold,
			DeploymentName:  "game-2048",
		},
		{
			ID:              "game-slice-master",
			Type:            ContentTypeGame,
			Theme:           "casual",
			Title:           "Slice Master",
			Description:     "Satisfying slicing action - cut everything!",
			ThumbnailURL:    "/assets/game-slice-master.png",
			ContainerStatus: StatusCold,
			DeploymentName:  "game-slice-master",
		},
		{
			ID:              "game-space-waves",
			Type:            ContentTypeGame,
			Theme:           "arcade",
			Title:           "Space Waves",
			Description:     "Dodge obstacles in space - one-tap arcade action",
			ThumbnailURL:    "/assets/game-space-waves.png",
			ContainerStatus: StatusCold,
			DeploymentName:  "game-space-waves",
		},
		{
			ID:              "game-drift-boss",
			Type:            ContentTypeGame,
			Theme:           "driving",
			Title:           "Drift Boss",
			Description:     "One-button drifting - how far can you go?",
			ThumbnailURL:    "/assets/game-drift-boss.png",
			ContainerStatus: StatusCold,
			DeploymentName:  "game-drift-boss",
		},
		{
			ID:              "game-tiny-fishing",
			Type:            ContentTypeGame,
			Theme:           "casual",
			Title:           "Tiny Fishing",
			Description:     "Relaxing fishing idle game - catch and upgrade",
			ThumbnailURL:    "/assets/game-tiny-fishing.png",
			ContainerStatus: StatusCold,
			DeploymentName:  "game-tiny-fishing",
		},
		{
			ID:              "game-stickman-hook",
			Type:            ContentTypeGame,
			Theme:           "physics",
			Title:           "Stickman Hook",
			Description:     "Swing through levels with grappling physics",
			ThumbnailURL:    "/assets/game-stickman-hook.png",
			ContainerStatus: StatusCold,
			DeploymentName:  "game-stickman-hook",
		},
		{
			ID:              "game-moto-x3m",
			Type:            ContentTypeGame,
			Theme:           "racing",
			Title:           "Moto X3M",
			Description:     "Extreme motorcycle racing with stunts",
			ThumbnailURL:    "/assets/game-moto-x3m.png",
			ContainerStatus: StatusCold,
			DeploymentName:  "game-moto-x3m",
		},
		{
			ID:              "game-paper-io-2",
			Type:            ContentTypeGame,
			Theme:           "territory",
			Title:           "Paper.io 2",
			Description:     "Claim territory in this multiplayer arena",
			ThumbnailURL:    "/assets/game-paper-io-2.png",
			ContainerStatus: StatusCold,
			DeploymentName:  "game-paper-io-2",
		},
		{
			ID:              "game-temple-of-boom",
			Type:            ContentTypeGame,
			Theme:           "action",
			Title:           "Temple of Boom",
			Description:     "Run and gun through temple dungeons",
			ThumbnailURL:    "/assets/game-temple-of-boom.png",
			ContainerStatus: StatusCold,
			DeploymentName:  "game-temple-of-boom",
		},
		{
			ID:              "game-monkey-mart",
			Type:            ContentTypeGame,
			Theme:           "idle",
			Title:           "Monkey Mart",
			Description:     "Run your own supermarket as a monkey",
			ThumbnailURL:    "/assets/game-monkey-mart.png",
			ContainerStatus: StatusCold,
			DeploymentName:  "game-monkey-mart",
		},
		{
			ID:              "game-tunnel-rush",
			Type:            ContentTypeGame,
			Theme:           "arcade",
			Title:           "Tunnel Rush",
			Description:     "Dodge obstacles in a high-speed tunnel",
			ThumbnailURL:    "/assets/game-tunnel-rush.png",
			ContainerStatus: StatusCold,
			DeploymentName:  "game-tunnel-rush",
		},
		{
			ID:              "game-narrow-one",
			Type:            ContentTypeGame,
			Theme:           "archery",
			Title:           "Narrow One",
			Description:     "Multiplayer archery capture-the-flag",
			ThumbnailURL:    "/assets/game-narrow-one.png",
			ContainerStatus: StatusCold,
			DeploymentName:  "game-narrow-one",
		},
		{
			ID:              "game-smash-karts",
			Type:            ContentTypeGame,
			Theme:           "racing",
			Title:           "Smash Karts",
			Description:     "3D multiplayer kart battle arena",
			ThumbnailURL:    "/assets/game-smash-karts.png",
			ContainerStatus: StatusCold,
			DeploymentName:  "game-smash-karts",
		},
		// FPS Arena
		{
			ID:              "game-shell-shockers",
			Type:            ContentTypeGame,
			Theme:           "fps",
			Title:           "Shell Shockers",
			Description:     "Egg-themed multiplayer FPS",
			ThumbnailURL:    "/assets/game-shell-shockers.png",
			ContainerStatus: StatusCold,
			DeploymentName:  "game-shell-shockers",
		},
		{
			ID:              "game-kour-io",
			Type:            ContentTypeGame,
			Theme:           "fps",
			Title:           "Kour.io",
			Description:     "Fast-paced multiplayer FPS",
			ThumbnailURL:    "/assets/game-kour-io.png",
			ContainerStatus: StatusCold,
			DeploymentName:  "game-kour-io",
		},
		{
			ID:              "game-voxiom-io",
			Type:            ContentTypeGame,
			Theme:           "fps",
			Title:           "Voxiom.io",
			Description:     "Voxel-based multiplayer shooter",
			ThumbnailURL:    "/assets/game-voxiom-io.png",
			ContainerStatus: StatusCold,
			DeploymentName:  "game-voxiom-io",
		},
		{
			ID:              "game-bullet-force",
			Type:            ContentTypeGame,
			Theme:           "fps",
			Title:           "Bullet Force",
			Description:     "Multiplayer FPS with custom loadouts",
			ThumbnailURL:    "/assets/game-bullet-force.png",
			ContainerStatus: StatusCold,
			DeploymentName:  "game-bullet-force",
		},
		{
			ID:              "game-skillwarz",
			Type:            ContentTypeGame,
			Theme:           "fps",
			Title:           "SkillWarz",
			Description:     "Tactical FPS arena combat",
			ThumbnailURL:    "/assets/game-skillwarz.png",
			ContainerStatus: StatusCold,
			DeploymentName:  "game-skillwarz",
		},
		{
			ID:              "game-buildnow-gg",
			Type:            ContentTypeGame,
			Theme:           "fps",
			Title:           "BuildNow GG",
			Description:     "Build and shoot multiplayer",
			ThumbnailURL:    "/assets/game-buildnow-gg.png",
			ContainerStatus: StatusCold,
			DeploymentName:  "game-buildnow-gg",
		},
		{
			ID:              "game-1v1-lol",
			Type:            ContentTypeGame,
			Theme:           "fps",
			Title:           "1v1.LOL",
			Description:     "Build and battle 1v1 shooter",
			ThumbnailURL:    "/assets/game-1v1-lol.png",
			ContainerStatus: StatusCold,
			DeploymentName:  "game-1v1-lol",
		},
		{
			ID:              "game-pixel-warfare",
			Type:            ContentTypeGame,
			Theme:           "fps",
			Title:           "Pixel Warfare",
			Description:     "Pixelated multiplayer FPS",
			ThumbnailURL:    "/assets/game-pixel-warfare.png",
			ContainerStatus: StatusCold,
			DeploymentName:  "game-pixel-warfare",
		},
		// Arcade Zone
		{
			ID:              "game-geometry-dash",
			Type:            ContentTypeGame,
			Theme:           "arcade",
			Title:           "Geometry Dash",
			Description:     "Rhythm-based platformer",
			ThumbnailURL:    "/assets/game-geometry-dash.png",
			ContainerStatus: StatusCold,
			DeploymentName:  "game-geometry-dash",
		},
		{
			ID:              "game-color-tunnel",
			Type:            ContentTypeGame,
			Theme:           "arcade",
			Title:           "Color Tunnel",
			Description:     "Colorful tunnel dodging game",
			ThumbnailURL:    "/assets/game-color-tunnel.png",
			ContainerStatus: StatusCold,
			DeploymentName:  "game-color-tunnel",
		},
		{
			ID:              "game-helix-jump",
			Type:            ContentTypeGame,
			Theme:           "arcade",
			Title:           "Helix Jump",
			Description:     "Bounce through helix tower",
			ThumbnailURL:    "/assets/game-helix-jump.png",
			ContainerStatus: StatusCold,
			DeploymentName:  "game-helix-jump",
		},
		{
			ID:              "game-stacky-bird",
			Type:            ContentTypeGame,
			Theme:           "arcade",
			Title:           "Stacky Bird",
			Description:     "Stack and fly bird game",
			ThumbnailURL:    "/assets/game-stacky-bird.png",
			ContainerStatus: StatusCold,
			DeploymentName:  "game-stacky-bird",
		},
		{
			ID:              "game-jet-rush",
			Type:            ContentTypeGame,
			Theme:           "arcade",
			Title:           "Jet Rush",
			Description:     "High-speed jet obstacle course",
			ThumbnailURL:    "/assets/game-jet-rush.png",
			ContainerStatus: StatusCold,
			DeploymentName:  "game-jet-rush",
		},
		{
			ID:              "game-count-masters",
			Type:            ContentTypeGame,
			Theme:           "arcade",
			Title:           "Count Masters",
			Description:     "Stickman crowd battle runner",
			ThumbnailURL:    "/assets/game-count-masters.png",
			ContainerStatus: StatusCold,
			DeploymentName:  "game-count-masters",
		},
		{
			ID:              "game-man-runner-2048",
			Type:            ContentTypeGame,
			Theme:           "arcade",
			Title:           "Man Runner 2048",
			Description:     "Merge and run number game",
			ThumbnailURL:    "/assets/game-man-runner-2048.png",
			ContainerStatus: StatusCold,
			DeploymentName:  "game-man-runner-2048",
		},
		// IO World
		{
			ID:              "game-agar-io",
			Type:            ContentTypeGame,
			Theme:           "io",
			Title:           "Agar.io",
			Description:     "Classic cell-eating IO game",
			ThumbnailURL:    "/assets/game-agar-io.png",
			ContainerStatus: StatusCold,
			DeploymentName:  "game-agar-io",
		},
		{
			ID:              "game-evowars-io",
			Type:            ContentTypeGame,
			Theme:           "io",
			Title:           "EvoWars.io",
			Description:     "Evolve and fight IO arena",
			ThumbnailURL:    "/assets/game-evowars-io.png",
			ContainerStatus: StatusCold,
			DeploymentName:  "game-evowars-io",
		},
		{
			ID:              "game-bloxd-io",
			Type:            ContentTypeGame,
			Theme:           "io",
			Title:           "Bloxd.io",
			Description:     "Block-based multiplayer world",
			ThumbnailURL:    "/assets/game-bloxd-io.png",
			ContainerStatus: StatusCold,
			DeploymentName:  "game-bloxd-io",
		},
		{
			ID:              "game-cubes-2048",
			Type:            ContentTypeGame,
			Theme:           "io",
			Title:           "Cubes 2048.io",
			Description:     "Merge cubes IO multiplayer",
			ThumbnailURL:    "/assets/game-cubes-2048.png",
			ContainerStatus: StatusCold,
			DeploymentName:  "game-cubes-2048",
		},
		{
			ID:              "game-diep-io",
			Type:            ContentTypeGame,
			Theme:           "io",
			Title:           "Diep.io",
			Description:     "Tank battle IO arena",
			ThumbnailURL:    "/assets/game-diep-io.png",
			ContainerStatus: StatusCold,
			DeploymentName:  "game-diep-io",
		},
		{
			ID:              "game-zombs-royale",
			Type:            ContentTypeGame,
			Theme:           "io",
			Title:           "Zombs Royale",
			Description:     "2D battle royale IO game",
			ThumbnailURL:    "/assets/game-zombs-royale.png",
			ContainerStatus: StatusCold,
			DeploymentName:  "game-zombs-royale",
		},
		{
			ID:              "game-snake-io",
			Type:            ContentTypeGame,
			Theme:           "io",
			Title:           "Snake.io",
			Description:     "Classic snake IO multiplayer",
			ThumbnailURL:    "/assets/game-snake-io.png",
			ContainerStatus: StatusCold,
			DeploymentName:  "game-snake-io",
		},
		{
			ID:              "game-skribbl-io",
			Type:            ContentTypeGame,
			Theme:           "io",
			Title:           "Skribbl.io",
			Description:     "Drawing and guessing game",
			ThumbnailURL:    "/assets/game-skribbl-io.png",
			ContainerStatus: StatusCold,
			DeploymentName:  "game-skribbl-io",
		},
		{
			ID:              "game-lol-beans",
			Type:            ContentTypeGame,
			Theme:           "io",
			Title:           "LOL Beans",
			Description:     "Fall guys style obstacle race",
			ThumbnailURL:    "/assets/game-lol-beans.png",
			ContainerStatus: StatusCold,
			DeploymentName:  "game-lol-beans",
		},
		{
			ID:              "game-fly-or-die",
			Type:            ContentTypeGame,
			Theme:           "io",
			Title:           "Fly or Die",
			Description:     "Evolving flying creature IO",
			ThumbnailURL:    "/assets/game-fly-or-die.png",
			ContainerStatus: StatusCold,
			DeploymentName:  "game-fly-or-die",
		},
		// Sports Hub
		{
			ID:              "game-basketbros",
			Type:            ContentTypeGame,
			Theme:           "sports",
			Title:           "BasketBros",
			Description:     "2D basketball brawler",
			ThumbnailURL:    "/assets/game-basketbros.png",
			ContainerStatus: StatusCold,
			DeploymentName:  "game-basketbros",
		},
		{
			ID:              "game-basketball-stars",
			Type:            ContentTypeGame,
			Theme:           "sports",
			Title:           "Basketball Stars",
			Description:     "1v1 basketball showdown",
			ThumbnailURL:    "/assets/game-basketball-stars.png",
			ContainerStatus: StatusCold,
			DeploymentName:  "game-basketball-stars",
		},
		{
			ID:              "game-goal-gang",
			Type:            ContentTypeGame,
			Theme:           "sports",
			Title:           "Goal Gang",
			Description:     "Multiplayer soccer action",
			ThumbnailURL:    "/assets/game-goal-gang.png",
			ContainerStatus: StatusCold,
			DeploymentName:  "game-goal-gang",
		},
		{
			ID:              "game-basket-random",
			Type:            ContentTypeGame,
			Theme:           "sports",
			Title:           "Basket Random",
			Description:     "Wacky basketball physics",
			ThumbnailURL:    "/assets/game-basket-random.png",
			ContainerStatus: StatusCold,
			DeploymentName:  "game-basket-random",
		},
		{
			ID:              "game-8-ball-pool",
			Type:            ContentTypeGame,
			Theme:           "sports",
			Title:           "8 Ball Pool",
			Description:     "Classic billiards game",
			ThumbnailURL:    "/assets/game-8-ball-pool.png",
			ContainerStatus: StatusCold,
			DeploymentName:  "game-8-ball-pool",
		},
		{
			ID:              "game-mini-golf",
			Type:            ContentTypeGame,
			Theme:           "sports",
			Title:           "Mini Golf Club",
			Description:     "Miniature golf course challenge",
			ThumbnailURL:    "/assets/game-mini-golf.png",
			ContainerStatus: StatusCold,
			DeploymentName:  "game-mini-golf",
		},
		{
			ID:              "game-crazy-flips",
			Type:            ContentTypeGame,
			Theme:           "sports",
			Title:           "Crazy Flips 3D",
			Description:     "Extreme gymnastics flips",
			ThumbnailURL:    "/assets/game-crazy-flips.png",
			ContainerStatus: StatusCold,
			DeploymentName:  "game-crazy-flips",
		},
		// Puzzle Lab
		{
			ID:              "game-uno-online",
			Type:            ContentTypeGame,
			Theme:           "puzzle",
			Title:           "Uno Online",
			Description:     "Classic card game online",
			ThumbnailURL:    "/assets/game-uno-online.png",
			ContainerStatus: StatusCold,
			DeploymentName:  "game-uno-online",
		},
		{
			ID:              "game-chess",
			Type:            ContentTypeGame,
			Theme:           "puzzle",
			Title:           "Chess",
			Description:     "Classic chess against AI or friends",
			ThumbnailURL:    "/assets/game-chess.png",
			ContainerStatus: StatusCold,
			DeploymentName:  "game-chess",
		},
		{
			ID:              "game-checkers",
			Type:            ContentTypeGame,
			Theme:           "puzzle",
			Title:           "Checkers",
			Description:     "Classic checkers board game",
			ThumbnailURL:    "/assets/game-checkers.png",
			ContainerStatus: StatusCold,
			DeploymentName:  "game-checkers",
		},
		{
			ID:              "game-backgammon",
			Type:            ContentTypeGame,
			Theme:           "puzzle",
			Title:           "Backgammon",
			Description:     "Classic backgammon board game",
			ThumbnailURL:    "/assets/game-backgammon.png",
			ContainerStatus: StatusCold,
			DeploymentName:  "game-backgammon",
		},
		{
			ID:              "game-mahjong",
			Type:            ContentTypeGame,
			Theme:           "puzzle",
			Title:           "Mahjong Solitaire",
			Description:     "Classic tile matching puzzle",
			ThumbnailURL:    "/assets/game-mahjong.png",
			ContainerStatus: StatusCold,
			DeploymentName:  "game-mahjong",
		},
		{
			ID:              "game-master-chess",
			Type:            ContentTypeGame,
			Theme:           "puzzle",
			Title:           "Master Chess",
			Description:     "Advanced chess with multiple modes",
			ThumbnailURL:    "/assets/game-master-chess.png",
			ContainerStatus: StatusCold,
			DeploymentName:  "game-master-chess",
		},
		{
			ID:              "game-mancala",
			Type:            ContentTypeGame,
			Theme:           "puzzle",
			Title:           "Mancala",
			Description:     "Ancient stone strategy game",
			ThumbnailURL:    "/assets/game-mancala.png",
			ContainerStatus: StatusCold,
			DeploymentName:  "game-mancala",
		},
		// Idle Kingdom
		{
			ID:              "game-clicker-heroes",
			Type:            ContentTypeGame,
			Theme:           "idle",
			Title:           "Clicker Heroes",
			Description:     "Classic idle clicker RPG",
			ThumbnailURL:    "/assets/game-clicker-heroes.png",
			ContainerStatus: StatusCold,
			DeploymentName:  "game-clicker-heroes",
		},
		{
			ID:              "game-mr-mine",
			Type:            ContentTypeGame,
			Theme:           "idle",
			Title:           "Mr. Mine",
			Description:     "Idle mining adventure",
			ThumbnailURL:    "/assets/game-mr-mine.png",
			ContainerStatus: StatusCold,
			DeploymentName:  "game-mr-mine",
		},
		{
			ID:              "game-doge-miner",
			Type:            ContentTypeGame,
			Theme:           "idle",
			Title:           "Doge Miner",
			Description:     "Mine to the moon with Doge",
			ThumbnailURL:    "/assets/game-doge-miner.png",
			ContainerStatus: StatusCold,
			DeploymentName:  "game-doge-miner",
		},
		{
			ID:              "game-doge-miner-2",
			Type:            ContentTypeGame,
			Theme:           "idle",
			Title:           "Doge Miner 2",
			Description:     "Doge mining sequel - to Mars!",
			ThumbnailURL:    "/assets/game-doge-miner-2.png",
			ContainerStatus: StatusCold,
			DeploymentName:  "game-doge-miner-2",
		},
		{
			ID:              "game-planet-clicker",
			Type:            ContentTypeGame,
			Theme:           "idle",
			Title:           "Planet Clicker",
			Description:     "Click to grow your planet",
			ThumbnailURL:    "/assets/game-planet-clicker.png",
			ContainerStatus: StatusCold,
			DeploymentName:  "game-planet-clicker",
		},
		{
			ID:              "game-race-clicker",
			Type:            ContentTypeGame,
			Theme:           "idle",
			Title:           "Race Clicker",
			Description:     "Tap to win the race",
			ThumbnailURL:    "/assets/game-race-clicker.png",
			ContainerStatus: StatusCold,
			DeploymentName:  "game-race-clicker",
		},
		{
			ID:              "game-idle-inventor",
			Type:            ContentTypeGame,
			Theme:           "idle",
			Title:           "Idle Inventor",
			Description:     "Invent and automate machines",
			ThumbnailURL:    "/assets/game-idle-inventor.png",
			ContainerStatus: StatusCold,
			DeploymentName:  "game-idle-inventor",
		},
		// Casual Play
		{
			ID:              "game-crazy-fish",
			Type:            ContentTypeGame,
			Theme:           "casual",
			Title:           "Crazy Fish",
			Description:     "Underwater fish adventure",
			ThumbnailURL:    "/assets/game-crazy-fish.png",
			ContainerStatus: StatusCold,
			DeploymentName:  "game-crazy-fish",
		},
		{
			ID:              "game-papas-pizzeria",
			Type:            ContentTypeGame,
			Theme:           "casual",
			Title:           "Papa's Pizzeria",
			Description:     "Run your own pizza shop",
			ThumbnailURL:    "/assets/game-papas-pizzeria.png",
			ContainerStatus: StatusCold,
			DeploymentName:  "game-papas-pizzeria",
		},
		{
			ID:              "game-getting-over-it",
			Type:            ContentTypeGame,
			Theme:           "casual",
			Title:           "Getting Over It",
			Description:     "Challenging climbing game",
			ThumbnailURL:    "/assets/game-getting-over-it.png",
			ContainerStatus: StatusCold,
			DeploymentName:  "game-getting-over-it",
		},
		{
			ID:              "game-friday-night-funkin",
			Type:            ContentTypeGame,
			Theme:           "casual",
			Title:           "Friday Night Funkin",
			Description:     "Rhythm-based music battle",
			ThumbnailURL:    "/assets/game-friday-night-funkin.png",
			ContainerStatus: StatusCold,
			DeploymentName:  "game-friday-night-funkin",
		},
		{
			ID:              "game-bubble-blast",
			Type:            ContentTypeGame,
			Theme:           "casual",
			Title:           "Bubble Blast",
			Description:     "Pop bubbles puzzle game",
			ThumbnailURL:    "/assets/game-bubble-blast.png",
			ContainerStatus: StatusCold,
			DeploymentName:  "game-bubble-blast",
		},
		{
			ID:              "game-fireboy-watergirl",
			Type:            ContentTypeGame,
			Theme:           "casual",
			Title:           "Fireboy & Watergirl",
			Description:     "Cooperative puzzle platformer",
			ThumbnailURL:    "/assets/game-fireboy-watergirl.png",
			ContainerStatus: StatusCold,
			DeploymentName:  "game-fireboy-watergirl",
		},
		// Racing & Karts
		{
			ID:              "game-night-city-racing",
			Type:            ContentTypeGame,
			Theme:           "racing",
			Title:           "Night City Racing",
			Description:     "Street racing at night",
			ThumbnailURL:    "/assets/game-night-city-racing.png",
			ContainerStatus: StatusCold,
			DeploymentName:  "game-night-city-racing",
		},
		{
			ID:              "game-mx-offroad",
			Type:            ContentTypeGame,
			Theme:           "racing",
			Title:           "MX Offroad Master",
			Description:     "Extreme offroad motorcycle racing",
			ThumbnailURL:    "/assets/game-mx-offroad.png",
			ContainerStatus: StatusCold,
			DeploymentName:  "game-mx-offroad",
		},
		// Battle Arena
		{
			ID:              "game-rooftop-snipers",
			Type:            ContentTypeGame,
			Theme:           "battle",
			Title:           "Rooftop Snipers",
			Description:     "Physics-based rooftop duels",
			ThumbnailURL:    "/assets/game-rooftop-snipers.png",
			ContainerStatus: StatusCold,
			DeploymentName:  "game-rooftop-snipers",
		},
		{
			ID:              "game-getaway-shootout",
			Type:            ContentTypeGame,
			Theme:           "battle",
			Title:           "Getaway Shootout",
			Description:     "Wacky escape and shoot game",
			ThumbnailURL:    "/assets/game-getaway-shootout.png",
			ContainerStatus: StatusCold,
			DeploymentName:  "game-getaway-shootout",
		},
		{
			ID:              "game-ragdoll-archers",
			Type:            ContentTypeGame,
			Theme:           "battle",
			Title:           "Ragdoll Archers",
			Description:     "Physics archery combat",
			ThumbnailURL:    "/assets/game-ragdoll-archers.png",
			ContainerStatus: StatusCold,
			DeploymentName:  "game-ragdoll-archers",
		},
		{
			ID:              "game-stickman-clash",
			Type:            ContentTypeGame,
			Theme:           "battle",
			Title:           "Stickman Clash",
			Description:     "Stickman army battles",
			ThumbnailURL:    "/assets/game-stickman-clash.png",
			ContainerStatus: StatusCold,
			DeploymentName:  "game-stickman-clash",
		},
		{
			ID:              "game-tank-stars",
			Type:            ContentTypeGame,
			Theme:           "battle",
			Title:           "Tank Stars",
			Description:     "Turn-based tank combat",
			ThumbnailURL:    "/assets/game-tank-stars.png",
			ContainerStatus: StatusCold,
			DeploymentName:  "game-tank-stars",
		},
		{
			ID:              "game-castle-craft",
			Type:            ContentTypeGame,
			Theme:           "battle",
			Title:           "Castle Craft",
			Description:     "Castle building and defense",
			ThumbnailURL:    "/assets/game-castle-craft.png",
			ContainerStatus: StatusCold,
			DeploymentName:  "game-castle-craft",
		},
		{
			ID:              "game-iron-legion",
			Type:            ContentTypeGame,
			Theme:           "battle",
			Title:           "Iron Legion",
			Description:     "Mech combat battle arena",
			ThumbnailURL:    "/assets/game-iron-legion.png",
			ContainerStatus: StatusCold,
			DeploymentName:  "game-iron-legion",
		},
		{
			ID:              "game-hex-empire",
			Type:            ContentTypeGame,
			Theme:           "battle",
			Title:           "Hex Empire",
			Description:     "Turn-based hex strategy",
			ThumbnailURL:    "/assets/game-hex-empire.png",
			ContainerStatus: StatusCold,
			DeploymentName:  "game-hex-empire",
		},
		{
			ID:              "game-rocket-bot-royale",
			Type:            ContentTypeGame,
			Theme:           "battle",
			Title:           "Rocket Bot Royale",
			Description:     "Tank battle royale",
			ThumbnailURL:    "/assets/game-rocket-bot-royale.png",
			ContainerStatus: StatusCold,
			DeploymentName:  "game-rocket-bot-royale",
		},
		{
			ID:              "game-horde-killer",
			Type:            ContentTypeGame,
			Theme:           "battle",
			Title:           "Horde Killer",
			Description:     "You vs 100 enemies",
			ThumbnailURL:    "/assets/game-horde-killer.png",
			ContainerStatus: StatusCold,
			DeploymentName:  "game-horde-killer",
		},
		{
			ID:              "game-superhot",
			Type:            ContentTypeGame,
			Theme:           "battle",
			Title:           "SuperHot",
			Description:     "Time moves when you move",
			ThumbnailURL:    "/assets/game-superhot.png",
			ContainerStatus: StatusCold,
			DeploymentName:  "game-superhot",
		},
		{
			ID:              "game-time-shooter-2",
			Type:            ContentTypeGame,
			Theme:           "battle",
			Title:           "Time Shooter 2",
			Description:     "Time-control FPS action",
			ThumbnailURL:    "/assets/game-time-shooter-2.png",
			ContainerStatus: StatusCold,
			DeploymentName:  "game-time-shooter-2",
		},
		{
			ID:              "game-street-fighter-2",
			Type:            ContentTypeGame,
			Theme:           "battle",
			Title:           "Street Fighter 2",
			Description:     "Classic fighting game",
			ThumbnailURL:    "/assets/game-street-fighter-2.png",
			ContainerStatus: StatusCold,
			DeploymentName:  "game-street-fighter-2",
		},
		// AI Service
		{
			ID:              "ai-service-tech",
			Type:            ContentTypeAIService,
			Theme:           "tech",
			Title:           "AI Assistant",
			Description:     "Smart AI helper powered by OpenAI",
			ThumbnailURL:    "/assets/ai-service.png",
			ContainerStatus: StatusCold,
			DeploymentName:  "ai-service",
		},
	}
}
