name: gavigo-ire
region: sgp

services:
  - name: orchestrator
    github:
      repo: ChanMeng666/gavigo
      branch: 001-ire-prototype
      deploy_on_push: true
    source_dir: /orchestrator
    environment_slug: go
    http_port: 8080
    instance_count: 1
    instance_size_slug: apps-s-1vcpu-0.5gb
    build_command: go mod download && go build -o bin/orchestrator ./cmd/orchestrator
    run_command: ./bin/orchestrator
    envs:
      - key: PORT
        value: "8080"
      - key: REDIS_ENABLED
        value: "false"
      - key: K8S_ENABLED
        value: "false"
      - key: LOG_LEVEL
        value: "info"
      - key: GOFLAGS
        value: "-insecure"
        scope: BUILD_TIME
      - key: GOSUMDB
        value: "off"
        scope: BUILD_TIME
    routes:
      - path: /api
      - path: /ws

static_sites:
  - name: frontend
    github:
      repo: ChanMeng666/gavigo
      branch: 001-ire-prototype
      deploy_on_push: true
    source_dir: /frontend
    build_command: npm install && npm run build
    output_dir: dist
    routes:
      - path: /
