name: gavigo-ire
region: sgp
features:
  - buildpack-stack=ubuntu-22

services:
  - name: orchestrator
    github:
      repo: ChanMeng666/gavigo
      branch: 001-ire-prototype
      deploy_on_push: true
    source_dir: orchestrator
    dockerfile_path: orchestrator/Dockerfile
    http_port: 8080
    instance_count: 1
    instance_size_slug: apps-s-1vcpu-0.5gb
    routes:
      - path: /api
      - path: /ws
    envs:
      - key: PORT
        value: "8080"
      - key: REDIS_URL
        value: ${redis.HOSTNAME}:${redis.PORT}
      - key: REDIS_PASSWORD
        value: ${redis.PASSWORD}
      - key: K8S_ENABLED
        value: "false"
      - key: LOG_LEVEL
        value: "info"
    health_check:
      http_path: /api/v1/health

static_sites:
  - name: frontend
    github:
      repo: ChanMeng666/gavigo
      branch: 001-ire-prototype
      deploy_on_push: true
    source_dir: frontend
    build_command: npm install && npm run build
    output_dir: dist
    routes:
      - path: /
    envs:
      - key: VITE_API_URL
        value: ${APP_URL}

databases:
  - name: redis
    engine: REDIS
    version: "7"
    size: db-s-dev-database
    num_nodes: 1
