name: gavigo-ire
region: sgp

static_sites:
  - name: frontend
    github:
      repo: ChanMeng666/gavigo
      branch: 001-ire-prototype
      deploy_on_push: true
    source_dir: /frontend
    build_command: npm install && npm run build
    output_dir: dist
    routes:
      - path: /
